#! /usr/bin python3
from Bio.Seq import Seq

# Look up inputs on NCBI database
gene_name = input("What is the gene name? ")
organism_name = input("What is the organism name? ")
locus_name = input("What is the locus name? ")
# Put API lookup on NCBI database stuff here#
# datasets download gene gene-id <gene_id>
# datasets download gene symbol brca1 --taxon mouse
# dsets summary gene gene-id 4171635

#NC_008223.1:8207-8374 is nucleotide position (start and end).
#ATP8
#>NC_008223.1:8207-8374 Squalogadus modificatus mitochondrion, complete genome
#ATGCCTCAACTAAACCCTGATCCCTGATTTATAATTTTTATTCTTACATGAGGAATTTTCCTAGCAGTCCTCCCCTTTAAAGTTATAGGACATATTTTCCCCAACGAACCCACCCCTAAAAGTATAATAACCCCTAAAACCACCCCCTGAAACTGACCATGACACTAA
#ND6
#>NC_008223.1:c14600-14079 Squalogadus modificatus mitochondrion, complete genome
#ATGACATATGTTATATTGACTCTTTTAATTGGGGTAATTTTTGGTGTAATTTCAGTAGCGTCAAATCCTTCTCCTTATTTTGCTGCTTTGGGGCTTGTTTTATTAGCGGGTGTGGGGTGTGGGATTTTAATTGGGCATGGTGGGTCGTTTCTATCTCTTGTATTATTTTTAATTTATTTAGGTGGGATGCTTGTTGTATTTGCTTATTGTGCAGCTTTGGCTGCAGAGCCTTACCCTGAGGCTTGGGGGGAGTGGTCCATCTTGGGGTCTGTATTAGGCTATTTTTCATTAGTTCTTGGGGCATTATTTTGGTTTGTAGGGGGGTGACATGAGGGGGCTTGAGTTCCTGCTGATGAGTTAATTGAATTTTCTGTGGTTTCTGGAGATTCAGCAGGGGTGGCTATGATATATTCTTTAGGGGGAGGTATACTTATTATTGGTGCTTGGGTTCTTTTATTAGCTTTATTTGTGGTGTTAGAGCTTGCGCGTGGTCGAGCCTGAGGGACAATGCGAGCAGTTAGA

gene_name = "ATP8"
cds_1 = "ATGCCTCAACTAAACCCTGATCCCTGATTTATAATTTTTATTCTTACATGAGGAATTTTCCTAGCAGTCCTCCCCTTTAAAGTTATAGGACATATTTTCCCCAACGAACCCACCCCTAAAAGTATAATAACCCCTAAAACCACCCCCTGAAACTGACCATGACACTAA"
# cds_2 nucleotide 6 was changed from T to G, but amino acid remains Proline.
cds_2 = "ATGCCGCAACTAAACCCTGATCCCTGATTTATAATTTTTATTCTTACATGAGGAATTTTCCTAGCAGTCCTCCCCTTTAAAGTTATAGGACATATTTTCCCCAACGAACCCACCCCTAAAAGTATAATAACCCCTAAAACCACCCCCTGAAACTGACCATGACACTAA"
# cds_3 nucleotide 9 was changed from A to T and the amino acid changed from Glutamine to Histidine.
cds_3 = "ATGCCTCATCTAAACCCTGATCCCTGATTTATAATTTTTATTCTTACATGAGGAATTTTCCTAGCAGTCCTCCCCTTTAAAGTTATAGGACATATTTTCCCCAACGAACCCACCCCTAAAAGTATAATAACCCCTAAAACCACCCCCTGAAACTGACCATGACACTAA"

cds_1 = Seq(cds_1)
cds_1_aa = cds_1.translate()
cds_2 = Seq(cds_2)
cds_2_aa = cds_2.translate()
cds_3 = Seq(cds_3)
cds_3_aa = cds_3.translate()

# Printing
print("Gene_name: " + gene_name)
print("Coding_sequence_1: " + cds_1)
print("Amino_acid_sequence_1: " + cds_1_aa)
print("Coding_sequence_2: " + cds_2)
print("Amino_acid_sequence_2: " + cds_2_aa)
print("Coding_sequence_3: " + cds_3)
print("Amino_acid_sequence_3: " + cds_3_aa)


